repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
    - id: trailing-whitespace
-   repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.73.0
    hooks:
        - id: terraform_fmt
        - id: terraform_validate
        - id: terraform_docs
          args:
            - --args=--config=.terraform-docs.yml