name: Terraform CI

on:
  push:
  merge_group:
    types: [checks_requested]

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.5"

      - run: terraform init

      - run: terraform validate

      - run: terraform fmt -recursive -check
