name: Terraform CI

on:
  push:
  merge_group:
    types: [checks_requested]

jobs:
  build:
    uses: meshcloud/shared-workflows/.github/workflows/terraform-meshplatform-modules-build-workflow.yml@main
